[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
include = """
(
    ^/tests/
  | ^/src/miroslava/
  | ^/setup[.]py
)
"""
exclude = """
(
    __pycache__
)
"""
